package org.lastfm.action;

public enum ActionResult {
	SUCCESS, FAILURE, ERROR, NOT_SCROBBLEABLE, SESSIONLESS, METADATA_SUCCESS, METADATA_ERROR, METADATA_NOT_FOUND, WRITE_METADATA_ERROR, UPDATED, LOGGED_OUT, COVER_ART_ERROR, COVER_ART_SUCCESS, METADATA_COMPLETE
}
