package org.lastfm.action;

public enum ActionResult {
	SUCCESS, FAILURE, ERROR, NOT_SCROBBLEABLE, SESSIONLESS, METADATA_SUCCESS, METADATA_ERROR, METADATA_NOT_FOUND, WRITE_METADATA_ERROR, UPDATED, LOGGED_OUT
}
