package org.lastfm.action;

public enum ActionResult {
	SUCCESS, FAILURE, ERROR, NOT_SCROBBLEABLE, SESSIONLESS, METADATA_SUCCESS, METADATA_ERROR, METADATA_NOT_FOUND, WRITE_METADATA_ERROR, UPDATED, LOGGED_OUT, LAST_FM_ERROR, LAST_FM_SUCCESS, METADATA_COMPLETE, NOT_ENOUGH_ARGUMENTS, YEAR_SUCCESS, YEAR_ERROR, GENRE_SUCCESS, GENRE_ERROR
}
